steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/finance-aidvisor-app:latest', '-f', 'Dockerfile_gcp', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/finance-aidvisor-app:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: [
    '-c',
    'gcloud run deploy finance-aidvisor-app --image gcr.io/$PROJECT_ID/finance-aidvisor-app:latest
    --region us-central1
    --set-env-vars TAVILY_API_KEY=$$TAVILY_API_KEY
    --set-env-vars VOYAGE_API_KEY=$$VOYAGE_API_KEY
    --set-env-vars GROQ_API_KEY=$$GROQ_API_KEY
    --set-env-vars COHERE_API_KEY=$$COHERE_API_KEY
    --set-env-vars LANGSMITH_API_KEY=$$LANGSMITH_API_KEY
    --set-env-vars QDRANT_API_KEY=$$QDRANT_API_KEY
    --cpu 2 --memory 512Mi --port 8501 --allow-unauthenticated --platform managed
    '
  ]

  secretEnv: [
    'TAVILY_API_KEY',
    'VOYAGE_API_KEY',
    'GROQ_API_KEY',
    'COHERE_API_KEY',
    'LANGSMITH_API_KEY',
    'QDRANT_API_KEY'
  ]

images:
- 'gcr.io/$PROJECT_ID/finance-aidvisor-app:latest'
timeout: 3600s

availableSecrets:
  secretManager:
  - versionName: projects/79854741196/secrets/TAVILY_API_KEY/versions/latest
    env: 'TAVILY_API_KEY'
  - versionName: projects/79854741196/secrets/VOYAGE_API_KEY/versions/latest
    env: 'VOYAGE_API_KEY'
  - versionName: projects/79854741196/secrets/GROQ_API_KEY/versions/latest
    env: 'GROQ_API_KEY'
  - versionName: projects/79854741196/secrets/COHERE_API_KEY/versions/latest
    env: 'COHERE_API_KEY'
  - versionName: projects/79854741196/secrets/LANGSMITH_API_KEY/versions/latest
    env: 'LANGSMITH_API_KEY'
  - versionName: projects/79854741196/secrets/QDRANT_API_KEY/versions/latest
    env: 'QDRANT_API_KEY'