# docker-compose for local run only
version: '3'
services:
  # start qdrant locally
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   volumes:
  #     - ./qdrant_storage:/qdrant/storage:z
  #   restart: always

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile_local
    ports:
      - "8000:8000"
      - "8501:8501"
    env_file:
      - app/.env
    # depends_on:
    #   - qdrant
