FROM python:3.11-slim

RUN pip install poetry==1.6.1

RUN poetry config virtualenvs.create false

WORKDIR /code

COPY ./pyproject.toml ./README.md ./poetry.lock* ./

COPY ./package[s] ./packages

RUN poetry install  --no-interaction --no-ansi --no-root

#gcloud_app includes getting api keys from environment variables, so no need to set ENV variables
COPY ./app ./app

COPY start.sh ./

EXPOSE 8000 8501

CMD ["bash", "start.sh"]
